org.apache.camel.FailedToCreateRouteException: Failed to create route route106 at: >>> To[kafka:{{kafka.topic.sx}}?brokers{{kafka.brokers}}&clientId=xxxxxx] <<< in route: Route(route106)[From[direct:send.sx.to.kafka] -> [Log[Send S... because of Failed to resolve endpoint: kafka:{{kafka.topic.sx}}?brokers{{kafka.brokers}}&clientId=xxxxxx due to: Property with key [kafka.topic.sx] not found in properties from text: kafka:{{kafka.topic.sx}}?brokers{{kafka.brokers}}&clientId={{kafka.client-id.anshar}}